### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by paoloantinori** [sequenceiq/hadoop-docker#14]
```
$ docker -v
Docker version 1.2.0, build fa7b24f/1.2.0

docker run -i -t sequenceiq/hadoop-docker:2.5.1 /etc/bootstrap.sh -bash
/
Starting sshd:                                             [  OK  ]
Starting namenodes on [cbd10023ac94]
Starting secondary namenodes [0.0.0.0]
starting yarn daemons
starting resourcemanager, logging to /usr/local/hadoop/logs/yarn--resourcemanager-cbd10023ac94.out



bash-4.1# cd $HADOOP_PREFIX
bash-4.1# # run the mapreduce
bash-4.1# bin/hadoop jar share/hadoop/mapreduce/hadoop-mapreduce-examples-2.5.1.jar grep input output 'dfs[a-z.]+'
14/10/08 11:51:18 INFO client.RMProxy: Connecting to ResourceManager at /0.0.0.0:8032
java.net.ConnectException: Call From cbd10023ac94/172.17.0.5 to cbd10023ac94:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:783)
    at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:730)
    at org.apache.hadoop.ipc.Client.call(Client.java:1415)
    at org.apache.hadoop.ipc.Client.call(Client.java:1364)
    at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:206)
    at com.sun.proxy.$Proxy14.delete(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
    at com.sun.proxy.$Proxy14.delete(Unknown Source)
    at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.delete(ClientNamenodeProtocolTranslatorPB.java:490)
    at org.apache.hadoop.hdfs.DFSClient.delete(DFSClient.java:1726)
    at org.apache.hadoop.hdfs.DistributedFileSystem$11.doCall(DistributedFileSystem.java:588)
    at org.apache.hadoop.hdfs.DistributedFileSystem$11.doCall(DistributedFileSystem.java:584)
    at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
    at org.apache.hadoop.hdfs.DistributedFileSystem.delete(DistributedFileSystem.java:584)
    at org.apache.hadoop.examples.Grep.run(Grep.java:95)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
    at org.apache.hadoop.examples.Grep.main(Grep.java:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:72)
    at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:145)
    at org.apache.hadoop.examples.ExampleDriver.main(ExampleDriver.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
Caused by: java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
    at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
    at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:529)
    at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:493)
    at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:606)
    at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:700)
    at org.apache.hadoop.ipc.Client$Connection.access$2800(Client.java:367)
    at org.apache.hadoop.ipc.Client.getConnection(Client.java:1463)
    at org.apache.hadoop.ipc.Client.call(Client.java:1382)
    ... 31 more
```

**Comment by tgpfeiffer** [comment]
Just ran into exactly this issue, good to see that it's fixed. Will you also update the image in Docker hub, (because apparently the image there still has the issue)?

**Comment by matyix** [comment]
Yes, this has been updated only in `master`. Any Hadoop version/branch you are looking in particular?

**Comment by tgpfeiffer** [comment]
2.6.0 would be great ;-)

**Comment by matyix** [comment]
Hi - I made/have pushed the change into 2.6, should be now available on Docker.io

**Comment by tgpfeiffer** [comment]
Great, thank you!

**Comment by jeacott** [comment]
same issue on latest pulled yesterday, running ubuntu 14.04
manual start as indicated above works.  
selinux is not installed.

**Comment by Gnork** [comment]
@jeacott I ran into the same problem with Ubuntu 14.04. Instead of selinux Ubuntu is using AppArmor, which is a similar thing. Disabling AppArmor solved the problem for me.
For disabling and enabling AppArmor see https://help.ubuntu.com/community/AppArmor

**Comment by jeacott** [comment]
Interesting,  although docker represents a big enough security risk already, i dont think i like the idea of compounding the issue. I did get this working without disabling anything but its so long ago i forgrt what now.

**Comment by Gnork** [comment]
My last post was a little too overhasty, because disabling AppArmor did not solve it entirely and I agree with jeacott that one should not disable AppArmor entirely. So too help out future readers: get the latest stable docker version (currently 1.8.3)  from the official docker repository (http://docs.docker.com/installation/ubuntulinux/) instead of installing the old docker version 1.0.1 in the Ubuntu 14.04 repos. "sudo docker -v" shows version.
