### ISSUE TITLE
How do I enable simple auth - SIMPLE authentication is not enabled.  Available:[TOKEN]

### ISSUE THREAD

**Issue by RichardHightower** [sequenceiq/hadoop-docker#43]
```sh
$ hadoop fs -fs hdfs://192.168.99.100:32846 -ls
16/02/07 15:11:53 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
ls: SIMPLE authentication is not enabled.  Available:[TOKEN]
```

I am getting the same error from Spark

```java

        final SparkConf sparkConfig = new SparkConf().setAppName("baseball");

        if (args.length == 0) {
            sparkConfig.setMaster("local[4]");
        }

        final JavaSparkContext sparkContext = new JavaSparkContext(sparkConfig);
        //final JavaRDD<String> lines = sparkContext.textFile("/opt/baseball/Master.csv");
        final JavaRDD<String> lines = sparkContext.textFile("hdfs://192.168.99.100:32846/opt/baseball/Master.csv");

        final JavaRDD<String> noHeader = lines.filter(line -> !line.startsWith("playerID"));
```

```
Exception in thread "main" org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled.  Available:[TOKEN]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:106)
	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:73)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1681)
	at org.apache.hadoop.hdfs.DistributedFileSystem$17.doCall(DistributedFileSystem.java:1106)
	at org.apache.hadoop.hdfs.DistributedFileSystem$17.doCall(DistributedFileSystem.java:1102)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	
```

**Comment by amryousry92** [comment]
I have the same issue?
Have you reached anything?

**Comment by biharitomi** [comment]
Hi,

[There is a thread about this issue here.] (https://community.hortonworks.com/questions/7896/simple-authentication-is-not-enabled-availabletoke.html)

Br,
Tamas

**Comment by amryousry92** [comment]
Hi,

I saw that thread and made changes to core-site.xml yet it didn't solve the issue.

**Comment by HDeiro** [comment]
Updates?
